services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: olayinka
      POSTGRES_PASSWORD: password
      PGDATA: /data/postres
#      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432-5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: false
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
      image: openzipkin/zipkin
      container_name: zipkin
      ports:
        - 9411:9411


  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:




