
spring:
  application:
    name: eureka-server
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

